### ISSUE TITLE
Add support for Metamask

### ISSUE THREAD

**Issue by lf94** [FindETH/wallets#180]
I will provide a PR.

**Comment by Mrtenz** [comment]
While I'd like to add support for MetaMask, the problem is that you cannot simply derive addresses from MetaMask. Every address needs to be added by the user manually, which defeats the point of FindETH. This library is aimed at HD wallets supporting BIP-32/44, like Ledger and Trezor devices, and mnemonic/seed phrases.

**Comment by lf94** [comment]
Yeah ok, I see now after reviewing further the project has specific usecases in mind. I'm really sorry for the noise! I'll close the issue.

**Comment by Mrtenz** [comment]
No worries! Any suggestions are of course appreciated.

**Comment by lf94** [comment]
For what it's worth, I've been looking for a package which abstracts access to wallets which are accessible via the web browser, but I'm really surprised this was the closest thing I could find. Anyhow, just means I need to put in the time for my own.
